version: '3'  # version of compose format 

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  app:
    build: ./app  # path is relative to docker-compose.yml localtion        
    volumes:
      - ./app:/usr/src/app # mount point    
    ports:
      - 5001:80  # host:container
    depends_on:
      - db
volumes:
  postgres_data: